### ISSUE TITLE
Operator Mono Italic font support

### ISSUE THREAD

**Issue by Asim-Tahir** [idleberg/Hopscotch#14]
I have Operator Mono font but this color theme not support font ligatures and italic font type.

**Comment by idleberg** [comment]
It would have been helpful to know which editor you're using, since this theme is available for 25 platforms.

> this color theme not support font ligatures and italic font type

I don't see how a theme should be able to override font features such as ligatures. It's true though, that the theme defines the use of italics. I'm only aware of the use of italic text in Markdown documents, which works perfectly.

![Untitled-1](https://user-images.githubusercontent.com/1504938/62325172-62b5ce00-b4ab-11e9-9873-4228d5cf9118.png)

Should you be using Visual Studio Code by any chance, take note that you have to enable ligatures in the settings.

![Screenshot 2019-08-01 at 22 26 44](https://user-images.githubusercontent.com/1504938/62325220-7d884280-b4ab-11e9-8134-3bebdb600b9f.png)

PS: I'm using *Fira Code* for reference, since it's the only free, monospaced font with ligatures I'm aware of.

**Comment by Asim-Tahir** [comment]
Thanks for your answer @idleberg, I mean by the "font ligature" of Operator Mono, I mean the combination of letters in italics. And yes then I use fira code font at the moment. But I would love to use Operator Mono with this theme.

**Comment by Asim-Tahir** [comment]
And yes I use the vscode editor

**Comment by idleberg** [comment]
But still, a theme is not able to override the features of a font. As a quick test: do those ligatures work in other themes?

**Comment by Asim-Tahir** [comment]
Yes it supports Operator Mono in themes like Monkai Pro, Fantastic (Ayu, Darcula, Gruvbox, Material, Monokai, Slime, Oceanic, One) in Vscode

**Comment by idleberg** [comment]
I still cannot reproduce this. I've installed the Fantastic themes and switched between them, the ligatures are available in any of its includes themes. As suspected, there is no setting in those themes to control whether a to use ligatures. Enabling/disabling ligatures is a global setting in Visual Studio Code.

Again, I tested this with Fira Code. Why? Because it has ligatures and I don't intend to buy Operator Mono just to run this simple test. It also appears, that the original Operator Mono has no ligatures (at least not for coding). I found [this project](https://github.com/kiliman/operator-mono-lig) that patches the font to add (coding) ligatures.

Many fonts have ligatures for the letter sequences "fi" or "ff". As a simple test, you could use "Times" or "Fira Sans" and switch between themes. You will notice that the ligatures for "fi"/"ff" will be preserved for *any* theme.

**Comment by Asim-Tahir** [comment]
@idleberg Thanks for advice, If I can help you for Operator Mono's font ligature support. It would be great. And good work for you.
